name: Build on Push

on:
  push:
    branches:
      - feature/create-cli-for-socialite-feature


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: bond_socialite-linux
          - os: macOS-latest
            output-name: bond_socialite-mac
          - os: windows-latest
            output-name: bond_socialite-windows.exe

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter pub get
      - run: mkdir build
      - run: dart compile exe bin/bond_socialite.dart -o build/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v1
        with:
          name: native-executables
          path: build